/*
 * generated by Xtext 2.25.0
 */
package gameoflife;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GameoflifeDSLRuntimeModule extends AbstractGameoflifeDSLRuntimeModule {
}
