/*
 * generated by Xtext 2.25.0
 */
package gameoflife.parser.antlr;

import com.google.inject.Inject;
import gameoflife.parser.antlr.internal.InternalGameoflifeDSLParser;
import gameoflife.services.GameoflifeDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GameoflifeDSLParser extends AbstractAntlrParser {

	@Inject
	private GameoflifeDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGameoflifeDSLParser createParser(XtextTokenStream stream) {
		return new InternalGameoflifeDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GameStart";
	}

	public GameoflifeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GameoflifeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
