/*
 * generated by Xtext 2.25.0
 */
package gameoflife.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameoflifeDSLScopeProvider extends DelegatingScopeProvider {
}
