/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL.impl;

import gameoflife.gameoflifeDSL.DieRules;
import gameoflife.gameoflifeDSL.GameoflifeDSLPackage;
import gameoflife.gameoflifeDSL.SurroundingCheck;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Die Rules</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.impl.DieRulesImpl#getSurroundingCheck <em>Surrounding Check</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DieRulesImpl extends MinimalEObjectImpl.Container implements DieRules
{
  /**
   * The cached value of the '{@link #getSurroundingCheck() <em>Surrounding Check</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSurroundingCheck()
   * @generated
   * @ordered
   */
  protected SurroundingCheck surroundingCheck;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DieRulesImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GameoflifeDSLPackage.Literals.DIE_RULES;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SurroundingCheck getSurroundingCheck()
  {
    return surroundingCheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSurroundingCheck(SurroundingCheck newSurroundingCheck, NotificationChain msgs)
  {
    SurroundingCheck oldSurroundingCheck = surroundingCheck;
    surroundingCheck = newSurroundingCheck;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK, oldSurroundingCheck, newSurroundingCheck);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSurroundingCheck(SurroundingCheck newSurroundingCheck)
  {
    if (newSurroundingCheck != surroundingCheck)
    {
      NotificationChain msgs = null;
      if (surroundingCheck != null)
        msgs = ((InternalEObject)surroundingCheck).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK, null, msgs);
      if (newSurroundingCheck != null)
        msgs = ((InternalEObject)newSurroundingCheck).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK, null, msgs);
      msgs = basicSetSurroundingCheck(newSurroundingCheck, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK, newSurroundingCheck, newSurroundingCheck));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK:
        return basicSetSurroundingCheck(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK:
        return getSurroundingCheck();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK:
        setSurroundingCheck((SurroundingCheck)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK:
        setSurroundingCheck((SurroundingCheck)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GameoflifeDSLPackage.DIE_RULES__SURROUNDING_CHECK:
        return surroundingCheck != null;
    }
    return super.eIsSet(featureID);
  }

} //DieRulesImpl
