/*
 * generated by Xtext 2.25.0
 */
package gameoflife.ui;

import com.google.inject.Injector;
import gameoflife.ui.internal.GameoflifeActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameoflifeDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GameoflifeActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GameoflifeActivator activator = GameoflifeActivator.getInstance();
		return activator != null ? activator.getInjector(GameoflifeActivator.GAMEOFLIFE_GAMEOFLIFEDSL) : null;
	}

}
