/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.Check#getCompare <em>Compare</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.Check#getInteger <em>Integer</em>}</li>
 * </ul>
 *
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getCheck()
 * @model
 * @generated
 */
public interface Check extends EObject
{
  /**
   * Returns the value of the '<em><b>Compare</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compare</em>' attribute.
   * @see #setCompare(String)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getCheck_Compare()
   * @model
   * @generated
   */
  String getCompare();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.Check#getCompare <em>Compare</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compare</em>' attribute.
   * @see #getCompare()
   * @generated
   */
  void setCompare(String value);

  /**
   * Returns the value of the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Integer</em>' attribute.
   * @see #setInteger(int)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getCheck_Integer()
   * @model
   * @generated
   */
  int getInteger();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.Check#getInteger <em>Integer</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Integer</em>' attribute.
   * @see #getInteger()
   * @generated
   */
  void setInteger(int value);

} // Check
