/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Die Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.DieRules#getSurroundingCheck <em>Surrounding Check</em>}</li>
 * </ul>
 *
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getDieRules()
 * @model
 * @generated
 */
public interface DieRules extends EObject
{
  /**
   * Returns the value of the '<em><b>Surrounding Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surrounding Check</em>' containment reference.
   * @see #setSurroundingCheck(SurroundingCheck)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getDieRules_SurroundingCheck()
   * @model containment="true"
   * @generated
   */
  SurroundingCheck getSurroundingCheck();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.DieRules#getSurroundingCheck <em>Surrounding Check</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Surrounding Check</em>' containment reference.
   * @see #getSurroundingCheck()
   * @generated
   */
  void setSurroundingCheck(SurroundingCheck value);

} // DieRules
