/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Evolution Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.EvolutionRules#getLiveRules <em>Live Rules</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.EvolutionRules#getDeadRules <em>Dead Rules</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.EvolutionRules#getBecomeAliveRules <em>Become Alive Rules</em>}</li>
 * </ul>
 *
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getEvolutionRules()
 * @model
 * @generated
 */
public interface EvolutionRules extends EObject
{
  /**
   * Returns the value of the '<em><b>Live Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.gameoflifeDSL.LiveRules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Live Rules</em>' containment reference list.
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getEvolutionRules_LiveRules()
   * @model containment="true"
   * @generated
   */
  EList<LiveRules> getLiveRules();

  /**
   * Returns the value of the '<em><b>Dead Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.gameoflifeDSL.DieRules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dead Rules</em>' containment reference list.
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getEvolutionRules_DeadRules()
   * @model containment="true"
   * @generated
   */
  EList<DieRules> getDeadRules();

  /**
   * Returns the value of the '<em><b>Become Alive Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.gameoflifeDSL.BecomeAliveRules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Become Alive Rules</em>' containment reference list.
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getEvolutionRules_BecomeAliveRules()
   * @model containment="true"
   * @generated
   */
  EList<BecomeAliveRules> getBecomeAliveRules();

} // EvolutionRules
