/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Start</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.GameStart#getInitialGrid <em>Initial Grid</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.GameStart#getEvolutionRules <em>Evolution Rules</em>}</li>
 * </ul>
 *
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getGameStart()
 * @model
 * @generated
 */
public interface GameStart extends EObject
{
  /**
   * Returns the value of the '<em><b>Initial Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initial Grid</em>' containment reference.
   * @see #setInitialGrid(InitialGrid)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getGameStart_InitialGrid()
   * @model containment="true"
   * @generated
   */
  InitialGrid getInitialGrid();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.GameStart#getInitialGrid <em>Initial Grid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initial Grid</em>' containment reference.
   * @see #getInitialGrid()
   * @generated
   */
  void setInitialGrid(InitialGrid value);

  /**
   * Returns the value of the '<em><b>Evolution Rules</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.gameoflifeDSL.EvolutionRules}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Evolution Rules</em>' containment reference list.
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getGameStart_EvolutionRules()
   * @model containment="true"
   * @generated
   */
  EList<EvolutionRules> getEvolutionRules();

} // GameStart
