/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GameoflifeDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gameoflifeDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.GameoflifeDSL.gameoflife";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gameoflifeDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameoflifeDSLPackage eINSTANCE = gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.GameStartImpl <em>Game Start</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.GameStartImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getGameStart()
   * @generated
   */
  int GAME_START = 0;

  /**
   * The feature id for the '<em><b>Initial Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_START__INITIAL_GRID = 0;

  /**
   * The feature id for the '<em><b>Evolution Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_START__EVOLUTION_RULES = 1;

  /**
   * The number of structural features of the '<em>Game Start</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_START_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.InitialGridImpl <em>Initial Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.InitialGridImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getInitialGrid()
   * @generated
   */
  int INITIAL_GRID = 1;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_GRID__CELLS = 0;

  /**
   * The feature id for the '<em><b>Lines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_GRID__LINES = 1;

  /**
   * The number of structural features of the '<em>Initial Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_GRID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.LineStatusImpl <em>Line Status</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.LineStatusImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getLineStatus()
   * @generated
   */
  int LINE_STATUS = 2;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_STATUS__COORDINATES = 0;

  /**
   * The number of structural features of the '<em>Line Status</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_STATUS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.LineCoordsImpl <em>Line Coords</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.LineCoordsImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getLineCoords()
   * @generated
   */
  int LINE_COORDS = 3;

  /**
   * The feature id for the '<em><b>Xbeg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_COORDS__XBEG = 0;

  /**
   * The feature id for the '<em><b>Xend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_COORDS__XEND = 1;

  /**
   * The feature id for the '<em><b>Ybeg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_COORDS__YBEG = 2;

  /**
   * The feature id for the '<em><b>Yend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_COORDS__YEND = 3;

  /**
   * The number of structural features of the '<em>Line Coords</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINE_COORDS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.CellStatusImpl <em>Cell Status</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.CellStatusImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getCellStatus()
   * @generated
   */
  int CELL_STATUS = 4;

  /**
   * The feature id for the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_STATUS__COORDINATES = 0;

  /**
   * The number of structural features of the '<em>Cell Status</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_STATUS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.CoordinatesImpl <em>Coordinates</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.CoordinatesImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getCoordinates()
   * @generated
   */
  int COORDINATES = 5;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATES__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATES__Y = 1;

  /**
   * The number of structural features of the '<em>Coordinates</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COORDINATES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.EvolutionRulesImpl <em>Evolution Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.EvolutionRulesImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getEvolutionRules()
   * @generated
   */
  int EVOLUTION_RULES = 6;

  /**
   * The feature id for the '<em><b>Live Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULES__LIVE_RULES = 0;

  /**
   * The feature id for the '<em><b>Dead Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULES__DEAD_RULES = 1;

  /**
   * The feature id for the '<em><b>Become Alive Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULES__BECOME_ALIVE_RULES = 2;

  /**
   * The number of structural features of the '<em>Evolution Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EVOLUTION_RULES_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.LiveRulesImpl <em>Live Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.LiveRulesImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getLiveRules()
   * @generated
   */
  int LIVE_RULES = 7;

  /**
   * The feature id for the '<em><b>Surrounding Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIVE_RULES__SURROUNDING_CHECK = 0;

  /**
   * The number of structural features of the '<em>Live Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIVE_RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.DieRulesImpl <em>Die Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.DieRulesImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getDieRules()
   * @generated
   */
  int DIE_RULES = 8;

  /**
   * The feature id for the '<em><b>Surrounding Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIE_RULES__SURROUNDING_CHECK = 0;

  /**
   * The number of structural features of the '<em>Die Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIE_RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.BecomeAliveRulesImpl <em>Become Alive Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.BecomeAliveRulesImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getBecomeAliveRules()
   * @generated
   */
  int BECOME_ALIVE_RULES = 9;

  /**
   * The feature id for the '<em><b>Surrounding Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BECOME_ALIVE_RULES__SURROUNDING_CHECK = 0;

  /**
   * The number of structural features of the '<em>Become Alive Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BECOME_ALIVE_RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.SurroundingCheckImpl <em>Surrounding Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.SurroundingCheckImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getSurroundingCheck()
   * @generated
   */
  int SURROUNDING_CHECK = 10;

  /**
   * The feature id for the '<em><b>Checks</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURROUNDING_CHECK__CHECKS = 0;

  /**
   * The feature id for the '<em><b>Extracheck</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURROUNDING_CHECK__EXTRACHECK = 1;

  /**
   * The number of structural features of the '<em>Surrounding Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SURROUNDING_CHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.CheckImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 11;

  /**
   * The feature id for the '<em><b>Compare</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__COMPARE = 0;

  /**
   * The feature id for the '<em><b>Integer</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__INTEGER = 1;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gameoflife.gameoflifeDSL.impl.ExtraCheckImpl <em>Extra Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gameoflife.gameoflifeDSL.impl.ExtraCheckImpl
   * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getExtraCheck()
   * @generated
   */
  int EXTRA_CHECK = 12;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRA_CHECK__OPERATOR = 0;

  /**
   * The feature id for the '<em><b>Check</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRA_CHECK__CHECK = 1;

  /**
   * The number of structural features of the '<em>Extra Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRA_CHECK_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.GameStart <em>Game Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Start</em>'.
   * @see gameoflife.gameoflifeDSL.GameStart
   * @generated
   */
  EClass getGameStart();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.GameStart#getInitialGrid <em>Initial Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Initial Grid</em>'.
   * @see gameoflife.gameoflifeDSL.GameStart#getInitialGrid()
   * @see #getGameStart()
   * @generated
   */
  EReference getGameStart_InitialGrid();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.GameStart#getEvolutionRules <em>Evolution Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Evolution Rules</em>'.
   * @see gameoflife.gameoflifeDSL.GameStart#getEvolutionRules()
   * @see #getGameStart()
   * @generated
   */
  EReference getGameStart_EvolutionRules();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.InitialGrid <em>Initial Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial Grid</em>'.
   * @see gameoflife.gameoflifeDSL.InitialGrid
   * @generated
   */
  EClass getInitialGrid();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.InitialGrid#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see gameoflife.gameoflifeDSL.InitialGrid#getCells()
   * @see #getInitialGrid()
   * @generated
   */
  EReference getInitialGrid_Cells();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.InitialGrid#getLines <em>Lines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lines</em>'.
   * @see gameoflife.gameoflifeDSL.InitialGrid#getLines()
   * @see #getInitialGrid()
   * @generated
   */
  EReference getInitialGrid_Lines();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.LineStatus <em>Line Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line Status</em>'.
   * @see gameoflife.gameoflifeDSL.LineStatus
   * @generated
   */
  EClass getLineStatus();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.LineStatus#getCoordinates <em>Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coordinates</em>'.
   * @see gameoflife.gameoflifeDSL.LineStatus#getCoordinates()
   * @see #getLineStatus()
   * @generated
   */
  EReference getLineStatus_Coordinates();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.LineCoords <em>Line Coords</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Line Coords</em>'.
   * @see gameoflife.gameoflifeDSL.LineCoords
   * @generated
   */
  EClass getLineCoords();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.LineCoords#getXbeg <em>Xbeg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xbeg</em>'.
   * @see gameoflife.gameoflifeDSL.LineCoords#getXbeg()
   * @see #getLineCoords()
   * @generated
   */
  EAttribute getLineCoords_Xbeg();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.LineCoords#getXend <em>Xend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xend</em>'.
   * @see gameoflife.gameoflifeDSL.LineCoords#getXend()
   * @see #getLineCoords()
   * @generated
   */
  EAttribute getLineCoords_Xend();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.LineCoords#getYbeg <em>Ybeg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ybeg</em>'.
   * @see gameoflife.gameoflifeDSL.LineCoords#getYbeg()
   * @see #getLineCoords()
   * @generated
   */
  EAttribute getLineCoords_Ybeg();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.LineCoords#getYend <em>Yend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Yend</em>'.
   * @see gameoflife.gameoflifeDSL.LineCoords#getYend()
   * @see #getLineCoords()
   * @generated
   */
  EAttribute getLineCoords_Yend();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.CellStatus <em>Cell Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell Status</em>'.
   * @see gameoflife.gameoflifeDSL.CellStatus
   * @generated
   */
  EClass getCellStatus();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.CellStatus#getCoordinates <em>Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Coordinates</em>'.
   * @see gameoflife.gameoflifeDSL.CellStatus#getCoordinates()
   * @see #getCellStatus()
   * @generated
   */
  EReference getCellStatus_Coordinates();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.Coordinates <em>Coordinates</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Coordinates</em>'.
   * @see gameoflife.gameoflifeDSL.Coordinates
   * @generated
   */
  EClass getCoordinates();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.Coordinates#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see gameoflife.gameoflifeDSL.Coordinates#getX()
   * @see #getCoordinates()
   * @generated
   */
  EAttribute getCoordinates_X();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.Coordinates#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see gameoflife.gameoflifeDSL.Coordinates#getY()
   * @see #getCoordinates()
   * @generated
   */
  EAttribute getCoordinates_Y();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.EvolutionRules <em>Evolution Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Evolution Rules</em>'.
   * @see gameoflife.gameoflifeDSL.EvolutionRules
   * @generated
   */
  EClass getEvolutionRules();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.EvolutionRules#getLiveRules <em>Live Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Live Rules</em>'.
   * @see gameoflife.gameoflifeDSL.EvolutionRules#getLiveRules()
   * @see #getEvolutionRules()
   * @generated
   */
  EReference getEvolutionRules_LiveRules();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.EvolutionRules#getDeadRules <em>Dead Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dead Rules</em>'.
   * @see gameoflife.gameoflifeDSL.EvolutionRules#getDeadRules()
   * @see #getEvolutionRules()
   * @generated
   */
  EReference getEvolutionRules_DeadRules();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.EvolutionRules#getBecomeAliveRules <em>Become Alive Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Become Alive Rules</em>'.
   * @see gameoflife.gameoflifeDSL.EvolutionRules#getBecomeAliveRules()
   * @see #getEvolutionRules()
   * @generated
   */
  EReference getEvolutionRules_BecomeAliveRules();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.LiveRules <em>Live Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Live Rules</em>'.
   * @see gameoflife.gameoflifeDSL.LiveRules
   * @generated
   */
  EClass getLiveRules();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.LiveRules#getSurroundingCheck <em>Surrounding Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Surrounding Check</em>'.
   * @see gameoflife.gameoflifeDSL.LiveRules#getSurroundingCheck()
   * @see #getLiveRules()
   * @generated
   */
  EReference getLiveRules_SurroundingCheck();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.DieRules <em>Die Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Die Rules</em>'.
   * @see gameoflife.gameoflifeDSL.DieRules
   * @generated
   */
  EClass getDieRules();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.DieRules#getSurroundingCheck <em>Surrounding Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Surrounding Check</em>'.
   * @see gameoflife.gameoflifeDSL.DieRules#getSurroundingCheck()
   * @see #getDieRules()
   * @generated
   */
  EReference getDieRules_SurroundingCheck();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.BecomeAliveRules <em>Become Alive Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Become Alive Rules</em>'.
   * @see gameoflife.gameoflifeDSL.BecomeAliveRules
   * @generated
   */
  EClass getBecomeAliveRules();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.BecomeAliveRules#getSurroundingCheck <em>Surrounding Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Surrounding Check</em>'.
   * @see gameoflife.gameoflifeDSL.BecomeAliveRules#getSurroundingCheck()
   * @see #getBecomeAliveRules()
   * @generated
   */
  EReference getBecomeAliveRules_SurroundingCheck();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.SurroundingCheck <em>Surrounding Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Surrounding Check</em>'.
   * @see gameoflife.gameoflifeDSL.SurroundingCheck
   * @generated
   */
  EClass getSurroundingCheck();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.SurroundingCheck#getChecks <em>Checks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Checks</em>'.
   * @see gameoflife.gameoflifeDSL.SurroundingCheck#getChecks()
   * @see #getSurroundingCheck()
   * @generated
   */
  EReference getSurroundingCheck_Checks();

  /**
   * Returns the meta object for the containment reference list '{@link gameoflife.gameoflifeDSL.SurroundingCheck#getExtracheck <em>Extracheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Extracheck</em>'.
   * @see gameoflife.gameoflifeDSL.SurroundingCheck#getExtracheck()
   * @see #getSurroundingCheck()
   * @generated
   */
  EReference getSurroundingCheck_Extracheck();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see gameoflife.gameoflifeDSL.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.Check#getCompare <em>Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Compare</em>'.
   * @see gameoflife.gameoflifeDSL.Check#getCompare()
   * @see #getCheck()
   * @generated
   */
  EAttribute getCheck_Compare();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.Check#getInteger <em>Integer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integer</em>'.
   * @see gameoflife.gameoflifeDSL.Check#getInteger()
   * @see #getCheck()
   * @generated
   */
  EAttribute getCheck_Integer();

  /**
   * Returns the meta object for class '{@link gameoflife.gameoflifeDSL.ExtraCheck <em>Extra Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extra Check</em>'.
   * @see gameoflife.gameoflifeDSL.ExtraCheck
   * @generated
   */
  EClass getExtraCheck();

  /**
   * Returns the meta object for the attribute '{@link gameoflife.gameoflifeDSL.ExtraCheck#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see gameoflife.gameoflifeDSL.ExtraCheck#getOperator()
   * @see #getExtraCheck()
   * @generated
   */
  EAttribute getExtraCheck_Operator();

  /**
   * Returns the meta object for the containment reference '{@link gameoflife.gameoflifeDSL.ExtraCheck#getCheck <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Check</em>'.
   * @see gameoflife.gameoflifeDSL.ExtraCheck#getCheck()
   * @see #getExtraCheck()
   * @generated
   */
  EReference getExtraCheck_Check();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GameoflifeDSLFactory getGameoflifeDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.GameStartImpl <em>Game Start</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.GameStartImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getGameStart()
     * @generated
     */
    EClass GAME_START = eINSTANCE.getGameStart();

    /**
     * The meta object literal for the '<em><b>Initial Grid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_START__INITIAL_GRID = eINSTANCE.getGameStart_InitialGrid();

    /**
     * The meta object literal for the '<em><b>Evolution Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_START__EVOLUTION_RULES = eINSTANCE.getGameStart_EvolutionRules();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.InitialGridImpl <em>Initial Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.InitialGridImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getInitialGrid()
     * @generated
     */
    EClass INITIAL_GRID = eINSTANCE.getInitialGrid();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_GRID__CELLS = eINSTANCE.getInitialGrid_Cells();

    /**
     * The meta object literal for the '<em><b>Lines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL_GRID__LINES = eINSTANCE.getInitialGrid_Lines();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.LineStatusImpl <em>Line Status</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.LineStatusImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getLineStatus()
     * @generated
     */
    EClass LINE_STATUS = eINSTANCE.getLineStatus();

    /**
     * The meta object literal for the '<em><b>Coordinates</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINE_STATUS__COORDINATES = eINSTANCE.getLineStatus_Coordinates();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.LineCoordsImpl <em>Line Coords</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.LineCoordsImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getLineCoords()
     * @generated
     */
    EClass LINE_COORDS = eINSTANCE.getLineCoords();

    /**
     * The meta object literal for the '<em><b>Xbeg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE_COORDS__XBEG = eINSTANCE.getLineCoords_Xbeg();

    /**
     * The meta object literal for the '<em><b>Xend</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE_COORDS__XEND = eINSTANCE.getLineCoords_Xend();

    /**
     * The meta object literal for the '<em><b>Ybeg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE_COORDS__YBEG = eINSTANCE.getLineCoords_Ybeg();

    /**
     * The meta object literal for the '<em><b>Yend</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LINE_COORDS__YEND = eINSTANCE.getLineCoords_Yend();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.CellStatusImpl <em>Cell Status</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.CellStatusImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getCellStatus()
     * @generated
     */
    EClass CELL_STATUS = eINSTANCE.getCellStatus();

    /**
     * The meta object literal for the '<em><b>Coordinates</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL_STATUS__COORDINATES = eINSTANCE.getCellStatus_Coordinates();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.CoordinatesImpl <em>Coordinates</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.CoordinatesImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getCoordinates()
     * @generated
     */
    EClass COORDINATES = eINSTANCE.getCoordinates();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATES__X = eINSTANCE.getCoordinates_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COORDINATES__Y = eINSTANCE.getCoordinates_Y();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.EvolutionRulesImpl <em>Evolution Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.EvolutionRulesImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getEvolutionRules()
     * @generated
     */
    EClass EVOLUTION_RULES = eINSTANCE.getEvolutionRules();

    /**
     * The meta object literal for the '<em><b>Live Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVOLUTION_RULES__LIVE_RULES = eINSTANCE.getEvolutionRules_LiveRules();

    /**
     * The meta object literal for the '<em><b>Dead Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVOLUTION_RULES__DEAD_RULES = eINSTANCE.getEvolutionRules_DeadRules();

    /**
     * The meta object literal for the '<em><b>Become Alive Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EVOLUTION_RULES__BECOME_ALIVE_RULES = eINSTANCE.getEvolutionRules_BecomeAliveRules();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.LiveRulesImpl <em>Live Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.LiveRulesImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getLiveRules()
     * @generated
     */
    EClass LIVE_RULES = eINSTANCE.getLiveRules();

    /**
     * The meta object literal for the '<em><b>Surrounding Check</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LIVE_RULES__SURROUNDING_CHECK = eINSTANCE.getLiveRules_SurroundingCheck();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.DieRulesImpl <em>Die Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.DieRulesImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getDieRules()
     * @generated
     */
    EClass DIE_RULES = eINSTANCE.getDieRules();

    /**
     * The meta object literal for the '<em><b>Surrounding Check</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIE_RULES__SURROUNDING_CHECK = eINSTANCE.getDieRules_SurroundingCheck();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.BecomeAliveRulesImpl <em>Become Alive Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.BecomeAliveRulesImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getBecomeAliveRules()
     * @generated
     */
    EClass BECOME_ALIVE_RULES = eINSTANCE.getBecomeAliveRules();

    /**
     * The meta object literal for the '<em><b>Surrounding Check</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BECOME_ALIVE_RULES__SURROUNDING_CHECK = eINSTANCE.getBecomeAliveRules_SurroundingCheck();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.SurroundingCheckImpl <em>Surrounding Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.SurroundingCheckImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getSurroundingCheck()
     * @generated
     */
    EClass SURROUNDING_CHECK = eINSTANCE.getSurroundingCheck();

    /**
     * The meta object literal for the '<em><b>Checks</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SURROUNDING_CHECK__CHECKS = eINSTANCE.getSurroundingCheck_Checks();

    /**
     * The meta object literal for the '<em><b>Extracheck</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SURROUNDING_CHECK__EXTRACHECK = eINSTANCE.getSurroundingCheck_Extracheck();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.CheckImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Compare</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__COMPARE = eINSTANCE.getCheck_Compare();

    /**
     * The meta object literal for the '<em><b>Integer</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK__INTEGER = eINSTANCE.getCheck_Integer();

    /**
     * The meta object literal for the '{@link gameoflife.gameoflifeDSL.impl.ExtraCheckImpl <em>Extra Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gameoflife.gameoflifeDSL.impl.ExtraCheckImpl
     * @see gameoflife.gameoflifeDSL.impl.GameoflifeDSLPackageImpl#getExtraCheck()
     * @generated
     */
    EClass EXTRA_CHECK = eINSTANCE.getExtraCheck();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTRA_CHECK__OPERATOR = eINSTANCE.getExtraCheck_Operator();

    /**
     * The meta object literal for the '<em><b>Check</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTRA_CHECK__CHECK = eINSTANCE.getExtraCheck_Check();

  }

} //GameoflifeDSLPackage
