/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage
 * @generated
 */
public interface GameoflifeDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GameoflifeDSLFactory eINSTANCE = gameoflife.gameoflifeDSL.impl.GameoflifeDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Game Start</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Start</em>'.
   * @generated
   */
  GameStart createGameStart();

  /**
   * Returns a new object of class '<em>Initial Grid</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Grid</em>'.
   * @generated
   */
  InitialGrid createInitialGrid();

  /**
   * Returns a new object of class '<em>Line Status</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Status</em>'.
   * @generated
   */
  LineStatus createLineStatus();

  /**
   * Returns a new object of class '<em>Line Coords</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Line Coords</em>'.
   * @generated
   */
  LineCoords createLineCoords();

  /**
   * Returns a new object of class '<em>Cell Status</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cell Status</em>'.
   * @generated
   */
  CellStatus createCellStatus();

  /**
   * Returns a new object of class '<em>Coordinates</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Coordinates</em>'.
   * @generated
   */
  Coordinates createCoordinates();

  /**
   * Returns a new object of class '<em>Evolution Rules</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Evolution Rules</em>'.
   * @generated
   */
  EvolutionRules createEvolutionRules();

  /**
   * Returns a new object of class '<em>Live Rules</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Live Rules</em>'.
   * @generated
   */
  LiveRules createLiveRules();

  /**
   * Returns a new object of class '<em>Die Rules</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Die Rules</em>'.
   * @generated
   */
  DieRules createDieRules();

  /**
   * Returns a new object of class '<em>Become Alive Rules</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Become Alive Rules</em>'.
   * @generated
   */
  BecomeAliveRules createBecomeAliveRules();

  /**
   * Returns a new object of class '<em>Surrounding Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Surrounding Check</em>'.
   * @generated
   */
  SurroundingCheck createSurroundingCheck();

  /**
   * Returns a new object of class '<em>Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Check</em>'.
   * @generated
   */
  Check createCheck();

  /**
   * Returns a new object of class '<em>Extra Check</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Extra Check</em>'.
   * @generated
   */
  ExtraCheck createExtraCheck();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GameoflifeDSLPackage getGameoflifeDSLPackage();

} //GameoflifeDSLFactory
