/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Coords</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.LineCoords#getXbeg <em>Xbeg</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.LineCoords#getXend <em>Xend</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.LineCoords#getYbeg <em>Ybeg</em>}</li>
 *   <li>{@link gameoflife.gameoflifeDSL.LineCoords#getYend <em>Yend</em>}</li>
 * </ul>
 *
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineCoords()
 * @model
 * @generated
 */
public interface LineCoords extends EObject
{
  /**
   * Returns the value of the '<em><b>Xbeg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xbeg</em>' attribute.
   * @see #setXbeg(int)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineCoords_Xbeg()
   * @model
   * @generated
   */
  int getXbeg();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.LineCoords#getXbeg <em>Xbeg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xbeg</em>' attribute.
   * @see #getXbeg()
   * @generated
   */
  void setXbeg(int value);

  /**
   * Returns the value of the '<em><b>Xend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xend</em>' attribute.
   * @see #setXend(int)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineCoords_Xend()
   * @model
   * @generated
   */
  int getXend();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.LineCoords#getXend <em>Xend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xend</em>' attribute.
   * @see #getXend()
   * @generated
   */
  void setXend(int value);

  /**
   * Returns the value of the '<em><b>Ybeg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ybeg</em>' attribute.
   * @see #setYbeg(int)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineCoords_Ybeg()
   * @model
   * @generated
   */
  int getYbeg();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.LineCoords#getYbeg <em>Ybeg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ybeg</em>' attribute.
   * @see #getYbeg()
   * @generated
   */
  void setYbeg(int value);

  /**
   * Returns the value of the '<em><b>Yend</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Yend</em>' attribute.
   * @see #setYend(int)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineCoords_Yend()
   * @model
   * @generated
   */
  int getYend();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.LineCoords#getYend <em>Yend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Yend</em>' attribute.
   * @see #getYend()
   * @generated
   */
  void setYend(int value);

} // LineCoords
