/**
 * generated by Xtext 2.25.0
 */
package gameoflife.gameoflifeDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Status</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gameoflifeDSL.LineStatus#getCoordinates <em>Coordinates</em>}</li>
 * </ul>
 *
 * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineStatus()
 * @model
 * @generated
 */
public interface LineStatus extends EObject
{
  /**
   * Returns the value of the '<em><b>Coordinates</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Coordinates</em>' containment reference.
   * @see #setCoordinates(LineCoords)
   * @see gameoflife.gameoflifeDSL.GameoflifeDSLPackage#getLineStatus_Coordinates()
   * @model containment="true"
   * @generated
   */
  LineCoords getCoordinates();

  /**
   * Sets the value of the '{@link gameoflife.gameoflifeDSL.LineStatus#getCoordinates <em>Coordinates</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Coordinates</em>' containment reference.
   * @see #getCoordinates()
   * @generated
   */
  void setCoordinates(LineCoords value);

} // LineStatus
