/*
 * generated by Xtext 2.25.0
 */
package gameoflife.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GameoflifeDSLUiModule extends AbstractGameoflifeDSLUiModule {

	public GameoflifeDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
