/*
 * generated by Xtext 2.25.0
 */
package gameoflife.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gameoflife.GameoflifeDSLRuntimeModule;
import gameoflife.GameoflifeDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GameoflifeDSLIdeSetup extends GameoflifeDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GameoflifeDSLRuntimeModule(), new GameoflifeDSLIdeModule()));
	}
	
}
